version: '3'
services: 
    postgres:
        image: 'postgres'
        # volumes: for mock data later
        #   - ./Docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        #   - ./Docker/extension.sql:/docker-entrypoint-initdb.d/extension.sql
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=workshop
        ports: 
          - "5432:5432"
    nsqlookupd:
      image: nsqio/nsq
      command: /nsqlookupd
      ports:
        - "4160:4160"
        - "4161:4161"
    nsqd:
      image: nsqio/nsq
      command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
      depends_on:
        - nsqlookupd
      ports:
        - "4150:4150"
        - "4151:4151"
    nsqadmin:
      image: nsqio/nsq
      command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
      depends_on:
        - nsqlookupd  
      ports:
        - "4171:4171"