version: '3'
services:
    nsqadmin:
        image: nsqio/nsq:latest
        command: ["./nsqadmin", "-lookupd-http-address", "nsqlookupd:4161"]
        ports: 
            - "4171:4171"
        networks:
            search-net:

networks:
    search-net:
        driver: bridge
        external: true
