version: '3'
services:
    nsqd:
        image: nsqio/nsq:latest
        command: ["./nsqd", "-broadcast-address", "localhost", "-lookupd-tcp-address", "nsqlookupd:4160"]
        ports: 
            - "4150:4150"
            - "4151:4151"
        networks:
            search-net:

networks:
    search-net:
        driver: bridge
        external: true
