version: '3'
services:
    postgres:
        image: postgres
        volumes:
          - ./fixtures/product.sql:/docker-entrypoint-initdb.d/product.sql
        ports: 
            - "5432:5432"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        networks:
            search-net:

networks:
    search-net:
        external: true
